site_name: Arquitectura Orientada a Servicios
nav:
  - Inicio: index.md
  - Configuracion de tu entorno: configuracion.md
  - Documentaci√≥n de servicios web: proyectos/index.md

theme:
  name: material
  locale: es
  language: es

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - mkdocs-click

plugins:
- mkdocstrings:
    handlers:
      python:
        locale: es
        paths:
          - tests
          - webservice